[package]
name = "sysi-overlay"
version = "0.1.35"
edition = "2021"
description = "A tiny transparent desktop overlay for Ubuntu"
license = "MIT"

[[bin]]
name = "sysi"
path = "src/main.rs"

[dependencies]
async-channel = "2.5"
cairo-rs = "0.18"
fs2 = "0.4"
gdk = "0.18"
gdkx11 = "0.18"
gdk-pixbuf = "0.18"
glib = "0.18"
gtk = "0.18"
libc = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
x11 = { version = "2.21", features = ["xlib"] }

[profile.release]
opt-level = "z"
lto = "thin"
codegen-units = 1
strip = true
panic = "abort"
